import raw from '@/content/pool.json'
import curation from '@/content/curation.json'
import type { Card } from './types'

type Curation = Record<string, { domain?: string; reason?: string }>

/**
 * The deck. Two files on purpose:
 *
 * - pool.json is machine-fetched and regenerated by scripts/build-pool.mjs.
 * - curation.json is written by people — the domain and the one-line reason.
 *
 * Keeping them apart means re-running the fetch never destroys editorial work, which
 * matters because the reason is the one thing on a card that no API returns.
 */
export const pool: Card[] = (raw as Card[]).map((card) => {
  const edit = (curation as Curation)[card.id] ?? {}
  return { ...card, domain: edit.domain ?? '', reason: edit.reason ?? '' }
})
